import {createRouter,createWebHashHistory} from "vue-router"
const Layout = ()=>import("../view/Layout.vue")
export default createRouter({
    history:createWebHashHistory(),
    routes:[
        {
            path:"/:pathMatch(.*)*",
            redirect:"/",
        },
        {
            path:"/login",
            component:()=>import("../view/Login/Login.vue"),
        },
        {
            path:"/",
            component:()=>import("../view/Home.vue"),
            redirect:"/home",
            children:[
                {
                    path:"home",
                    component:()=>import("../view/Home/Home.vue"),
                },
                {
                    path:"log-nakadai",
                    name:"日志中台",
                    component:Layout,
                    children:[
                        {
                            path:"application-management",
                            component:()=>import("../view/LogNakadai/ApplicationManagement.vue")
                        },
                        {
                            path:"application-type-management",
                            component:()=>import("../view/LogNakadai/ApplicationTypeManagement.vue")
                        },
                        {
                            path:"terminal",
                            component:()=>import("../view/LogNakadai/Terminal.vue")
                        }
                    ]
                },
            ]
        },
    ],
});